### ISSUE TITLE
private static let gvariantVarDictType = g_variant_type_new("a{sv}")

### ISSUE THREAD

**Issue by aadog** [frida/frida-swift#11]
private static let gvariantVarDictType = g_variant_type_new("a{sv}")

fix

private static let gvariantVarDictType = g_variant_type_new("{sv}")

**Comment by oleavr** [comment]
This is meant to be `a{sv}`, to match GLib's `G_VARIANT_TYPE_VARDICT` defined [here](https://gitlab.gnome.org/GNOME/glib/-/blob/37e5dfd3a2ced10c395b38702ae15e0e128e457b/glib/gvarianttype.h#L271).
