### ISSUE TITLE
Reference to `FridaDeviceManager` is ambiguous 

### ISSUE THREAD

**Issue by klmitchell2** [frida/frida-swift#5]
Hey 👋 , 

I am trying to install `frida-swift` but I receive this error when I attempt to run the tests. Building the framework does not produce errors, but I am getting this compile error:
![image](https://user-images.githubusercontent.com/5108164/85932885-edf33b80-b895-11ea-9dde-89ae512edda6.png)

This is happening for `FridaDevice`, `FridaSession`, and `FridaScript`.

**Comment by oleavr** [comment]
Hey!

This means the namespace we chose on the Swift side is unfortunuate, as it results in some of the Objective-C interop header types clashing with the C types. Either we will have to change our Swift namespace so this doesn't happen, or configure a different namespace for the Objective-C side only (if possible).

As a workaround you can probably disable generation of the Objective-C interop header.

**Comment by klmitchell2** [comment]
What would be the best way to disable the generation of the Objective-C inter header? I'm unsure if this a flag at `make core-macos-thin` or when generating the dev kit?

**Comment by oleavr** [comment]
It would be an Xcode project setting in frida-swift. I haven't investigated this but suspect it's in there somewhere.

**Comment by klmitchell2** [comment]
Found the setting in `Build Settings`: 

<img width="659" alt="image" src="https://user-images.githubusercontent.com/5108164/86079117-5f2d1d00-ba55-11ea-9453-c20d2f982a9f.png">

Changing from `Yes` to `No` fixed the issue.

**Comment by oleavr** [comment]
Yay. Could you open a PR to change this? Don't think we're missing out on anything by omitting this.
